### ISSUE TITLE
Help figuring out how to use this tool

### ISSUE THREAD

**Issue by WorksWellWithOthers** [adjacentlink/emane-jammer-simple#1]
Hello, I have two nodes communicating (can ping between each other).

TDMA NEM-1 and TDMA NEM-2

****
nem 1   phy ReceivePowerTable
| NEM | Frequency  | Rx Power       | Last Packet Time |
| 2   | 2400000000 | -74.9846920348 | 1647819076.01    |

I am trying to jam the two nodes and typed the following argument

./emane-jammer-simple 65534 2400000000 --power 30 -v

My understanding is that the first argument is the nem-id of the transmitter (jammer) and has to be a number that is not already assigned.  The second argument is the frequency to jam in Hz. 

What should I fix to get the result that I want?

**Comment by sgalgano** [comment]
Here is an example of jamming 2.4GHz with a 30dBm continuous tone and a transmit bandwidth of 20MHz using NEM id 11:

```bash
$ emane-jammer-simple \
    --power 30 \
    -i letce0 \
    --bandwidth 20000000 \
    11  \
    2400000000
```

Note:

1. You have to specify the interface for the OTA
2. The NEMs in your experiment need pathloss information for the jammer, in this case NEM 11, just like they do for all other NEMs in the experiment.

**Comment by WorksWellWithOthers** [comment]
I'm not sure what to use as the interface for the OTA. 

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000  
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00  

2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000  
    link/ether 08:00:27:d3:a0:32 brd ff:ff:ff:ff:ff:ff  

3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:c4:b3:49:82 brd ff:ff:ff:ff:ff:ff  

2314: emanenode0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000  
    link/ether fe:74:c0:a2:b7:62 brd ff:ff:ff:ff:ff:ff  

2316: veth1.1@if2315: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master emanenode0 state UP mode DEFAULT group default qlen 1000  
    link/ether fe:74:c0:a2:b7:62 brd ff:ff:ff:ff:ff:ff link-netnsid 0  

2318: veth1.2@if2317: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000  
    link/ether fe:46:d9:c1:57:ce brd ff:ff:ff:ff:ff:ff link-netnsid 0  

2320: veth2.1@if2319: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master emanenode0 state UP mode DEFAULT group default qlen 1000  
    link/ether fe:dc:11:5f:b0:a7 brd ff:ff:ff:ff:ff:ff link-netnsid 1  

2322: veth2.2@if2321: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000  
    link/ether fe:95:ed:f8:a1:a9 brd ff:ff:ff:ff:ff:ff link-netnsid 1
```

**Comment by sgalgano** [comment]
Use whatever interface you are using for the OTA or the bridge interface connecting them, if applicable.

For example, if you are using LXC containers running emane and you are jamming from *a container instance*, use whatever interface you have configured:

```xml
  <param name="otamanagerdevice" value="backchan0"/>
```

If you are connecting all the LXC OTA interfaces to a bridge on your LXC host, you can also run the script from the host using the bridge interface. I believe this is what you are doing, so use `emanenode0`.

**Comment by WorksWellWithOthers** [comment]
Got it working. Thank you.

**Comment by patelkb** [comment]
Make sure you have pathloss defined between the jammer and the other two nodes to achieve the desired noise level ar nodes 1 and 2.

Kaushik B Patel
Adjacent Link LLC
CEO, Director of Engineering
